### ISSUE TITLE
Move to Nextcloud organization

### ISSUE THREAD

**Issue by korelstar** [nextcloud/eslint-plugin-nextcloud#6]
This is a nice project that can ease app development. However, I like to see it to be an official repository by Nextcloud, i.e. this repository should be moved to https://github.com/nextcloud/

**Comment by ChristophWurst** [comment]
Fine by me :)

**Comment by ChristophWurst** [comment]
@rullzer can you help with that? I could transfer it to you and you pass it on. I do not have permission to move it directly.

**Comment by rullzer** [comment]
We could do that if you think it is ready @ChristophWurst

**Comment by ChristophWurst** [comment]
provided that you'll make me repo admin I'm fine with moving ;)

**Comment by ChristophWurst** [comment]
![Bildschirmfoto von 2019-05-21 11-20-53](https://user-images.githubusercontent.com/1374172/58084084-865ebd00-7bba-11e9-95b8-bd8681ad182d.png)

**Comment by rullzer** [comment]
> provided that you'll make me repo admin I'm fine with moving ;)

done and moved
